### ISSUE TITLE
[SUGGESTION] a web-app or browser extension that runs this code regardless of OS or device

### ISSUE THREAD

**Issue by imnotjack91** [jhead/phantom#101]
ive seen this method used more and more, where basically everything required for a specific program is able to be run from a web-app skipping the need to install and configure the program manually. i imagine this could be streamlined with a browser plugin and/or implemented as a mobile application much easier.

**Comment by Heath123** [comment]
An app is possible but a web browser can't access ports...

**Comment by jhead** [comment]
Hey @imnotjack91, unfortunately phantom requires fairly low-level networking access that I don't believe is possible in a browser extension. I'm actively looking into and prototyping a mobile app for iOS and Android, but no ETA on that just yet.

I've also considered adding a UI to phantom that you just use from your browser on your computer, so that you don't have to configure it manually from the command line. So that's definitely possible as well.
