### ISSUE TITLE
Looking for documentation for Dedicated Servers

### ISSUE THREAD

**Issue by DeFlanko** [jhead/phantom#113]
Ive been attempting to setup a Dedicated server on my own machine for xbox play.

Im looking for any guidance on how to utilize Phantom and Mojang's bedrock dedicated server running on the same server client.  If i try to run phantom and the dedicated server at the same time it has a port conflict of 19132. Im sure im not setting something up incorrectly. 

Is this how it should be setup?

{internet} = [FQDN:19132]
⬇
[ROUTER PORT FORWARDED 19132 to internal IP we'll call "localip"]
⬇
[On Server:

Running Phantom with: C:\Games\phantom-windows.exe -bind "localip" -bind_port 19133 -server FQDN:19132" 

Running in Parallel: **Bedrock-server.exe** with **server.properties** of:
server-port=19132
server-portv6= **disabled**
]

**Comment by joshuaxlino** [comment]
> Ive been attempting to setup a Dedicated server on my own machine for xbox play.
> 
> 
> 
> Im looking for any guidance on how to utilize Phantom and Mojang's bedrock dedicated server running on the same server client.  If i try to run phantom and the dedicated server at the same time it has a port conflict of 19132. Im sure im not setting something up incorrectly. 
> 
> 
> 
> Is this how it should be setup?
> 
> 
> 
> {internet} = [FQDN:19132]
> 
> ⬇
> 
> [ROUTER PORT FORWARDED 19132 to internal IP we'll call "localip"]
> 
> ⬇
> 
> [On Server:
> 
> 
> 
> Running Phantom with: C:\Games\phantom-windows.exe -bind "localip" -bind_port 19133 -server FQDN:19132" 
> 
> 
> 
> Running in Parallel: **Bedrock-server.exe** with **server.properties** of:
> 
> server-port=19132
> 
> server-portv6= **disabled**
> 
> ]
> 
> 
> 
> 

You do not need phantom to connect to LAN hosted servers.

**Comment by DeFlanko** [comment]
but it would be for those connecting via WAN on XBOX

**Comment by joshuaxlino** [comment]
> but it would be for those connecting via WAN on XBOX

You will join without phantom, and other people will connect with it. There have been issues with phantom connecting to BDS so i would recommend trying bedrockconnect for the people trying to join from other locations.

**Comment by DeFlanko** [comment]
i'll give Bedrock connect a go.  i assume this is also a GitHub project as well?

**Comment by joshuaxlino** [comment]
It is from github, he has posted tutorials for each console and how to use your DNS instead of his server DNS.

**Comment by DeFlanko** [comment]
as much as i value your alternative method and input on the issue, i'd like to see if @jhead has any input

**Comment by jhead** [comment]
Hey @DeFlanko! Thanks for the interest.

> it would be for those connecting via WAN on XBOX

phantom would help you connect to a remote Bedrock server on your Xbox if you weren't already running it locally on your LAN. If it _is_ on your LAN, then you won't need phantom to connect to it - as long as you have the LAN Broadcast setting enabled on the world, it'll show up on Xbox automatically.

For allowing other people outside your home/LAN to connect to your server on their consoles, they'll need to use their own method, which can either be phantom or the DNS trick mentioned above. In other words, phantom only works within a LAN and won't work over WAN.

As for configuring your server (not phantom) with port forwarding, everything looks correct there and it should allow remote players to connect.

>  If i try to run phantom and the dedicated server at the same time it has a port conflict of 19132.

This might be a bug in phantom - running a server locally alongside phantom isn't really supported at the moment, since running one locally by itself would cause it to show up on your Xbox, so there's no need for phantom.

Either way, the setup/command you describe above should work for anyone else trying to join your server, though `-bind "localip" -bind_port 19133` options are not needed. All they would need to do is run `phantom-windows.exe FQDN:19132` and, assuming your port forwarding is working, they should see the server on their Xbox.
