### ISSUE TITLE
Unconnected Pong

### ISSUE THREAD

**Issue by james090500** [jhead/phantom#163]
Trying to Connect a friend to my (Geyser)[https://geysermc.org/] server with this script but it's reporting a "Recieved Unconnected Pong from server.

I am not sure what else this could be. Without debug we are seeing connections trying to come in but nothing show on Xbox.

```bat
@echo off
phantom-windows.exe -server play.capecraft.net:19132 -6 -debug
pause
```

![image](https://user-images.githubusercontent.com/20372645/161987455-563e4dc2-1e9a-43e2-bdfa-431665218357.png)

![image](https://user-images.githubusercontent.com/20372645/161987360-3ff66468-4e54-490d-8de8-36b604ddb43e.png)

**Comment by adriandhart** [comment]
I am having the same problem. This issue started when I updated the server to Bedrock v1.19.

The server shows up on the Xbox Lan game list when I stop the server and the "Server Offline" message appears on the LAN Game server list. However, when I restart the server the game vanishes from the Lan Game list.

The server is definitely running because I can connect using Minecraft on a Windows computer or on the Xbox using the Bedrock Together app. 

Any help with this would be greatly appreciated. Thanks
