### ISSUE TITLE
I have gotten in command prompt to the folder, whats next?

### ISSUE THREAD

**Issue by mwalton07** [jhead/phantom#34]

**Comment by mwalton07** [comment]
![Command Prompt 11_27_2019 9_56_40 AM](https://user-images.githubusercontent.com/58263900/69734022-485bcc00-10fc-11ea-8daf-f6d5283f4dd3.png)

**Comment by jhead** [comment]
Hey @mwalton07! It looks like you downloaded the source code instead of one of the releases of phantom. This is the download you want: https://github.com/jhead/phantom/releases/tag/v0.2.1

Just download the correct one for your Windows PC, navigate to your downloads folder, and you should be able to run it from there.
