### ISSUE TITLE
Phantom only works on same network?

### ISSUE THREAD

**Issue by stiw91** [jhead/phantom#35]
This is more of a question than a statement; I think I misunderstood what this program does; I thought it could allow me to use my server with my friend on an Xbox without being on the same network, like a server, but the Xbox sees it as a LAN. Is it saying I can use it just as a LAN on the same WiFi, rather than an external server?

**Comment by jhead** [comment]
Hey @stiw91! Great question. phantom works in addition to a Minecraft server, making that server appear on your Xbox as a LAN server, when it's actually remote. That's useful because the Xbox version of Minecraft doesn't allow you to add external servers, but LAN servers show up automatically.

If you don't already have a Bedrock server, one option would be set one up on your computer using [the official server software](https://www.minecraft.net/en-us/download/server/bedrock/), or purchase one from a host like [CubedHost](https://cubedhost.com).

Once you have a server, you can run phantom and provide the server's IP, and it'll show up on any Xbox on the LAN.

**Comment by stiw91** [comment]
I see I can wait till they add official Xbox support to BDS (if they do)
