### ISSUE TITLE
Nintendo Switch Support

### ISSUE THREAD

**Issue by ham1255** [jhead/phantom#39]
just why?

**Comment by jhead** [comment]
From my understanding, the Switch has a separate Local Network Mode that only allows LAN play with other Switches and not all other LAN devices like the other platforms. I believe cross-play is still possible in general on the Switch if you're logged into a Microsoft account, but not simply over LAN, so phantom won't work.

We're always looking for new ways to improve phantom to support more platforms and make it easier to use. Let me know if you have any suggestions!

**Comment by ham1255** [comment]
what if you make something that tricks the swtich to make it thinking its another Nintendo switch?

**Comment by evan25lee** [comment]
Alright while this isn't a solution to making this work on a switch, there is a tool that does work on a switch until jhead does decide on if he wants to make this work with switch or not. https://github.com/nxminens/nxminens

**Comment by Liriel-666** [comment]
perhaps your Team can make a seperate Tool for the Switch because NXminens is old and no new Version seams to come.

**Comment by redpoisonv3** [comment]
> what if you make something that tricks the swtich to make it thinking its another Nintendo switch?
> or Making Xbox account bot (idk if it's against xbox tos) to trick Nintendo swtich that player is playing on his world?

There is a trick that I'm using that involves pi hole the DNS based ad blocker, I've got my switch convinced that I'm on a LAN connection, I changed the host record in the pi for the featureed server of the hive to instead of its IP address I changed it to the IP address of my server, but instead of using the default port numbers I changed it to 19180 ipv4 19181 ipv6, which made it appears as a LAN under  the switch freinds tab sent me a pm and I'll give you a hand with it if you are interested.

**Comment by jhead** [comment]
We’ve considered adding support for replacing the featured server list but it still requires the user to manually change their DNS settings on the device. If you forget about changing those later on, it can cause connectivity issues. 

There are some other tools out there that do this really well if you do want to go down that route.

I would consider supporting the Switch in some other more reliable way if we can find one.

**Comment by ProdigyGG** [comment]
Use this method https://youtu.be/0B5T3btxFy0
