### ISSUE TITLE
Local server, do I need phantom?

### ISSUE THREAD

**Issue by ndaman** [jhead/phantom#57]
I have a local bedrock server (running on a linux server via docker). I can connect to it from my PC by typing in the local IP address of the server, but it does not show up as a LAN game, and thus I cannot connect to it from my xbox. I am fairly confident that phantom would solve this issue, but I feel like I *should* be able to get it working without phantom. 

Sorry if this is off-topic, but this community seems more knowledgeable about bedrock servers than others.

**Comment by jhead** [comment]
Hey @ndaman! Your intuition is right in that you don’t need phantom, but you’re going to have some trouble getting the server to show up on LAN for other devices when running it in Docker. We have the same issue with running phantom inside Docker.

The issue is probably that the server listens for broadcasted ping packets that come over a destination address that’s different from your server’s IP address. For example, if your LAN is 10.0.0.0, they would be destined for 10.0.0.255 on port 19132. As far as I know, Docker doesn’t forward these down to the container, even if it exposes port 19132. 

You might be able to set the network on the container to host mode to pass the interface all the way through using --net=host.

**Comment by ndaman** [comment]
Thanks! I was wondering if there was an additional port that needed to be opened up. I'll try again with host net and with a local version if that doesn't work.

**Comment by ndaman** [comment]
I was ultimately able to get things working, although I'm not sure exactly which of the things I did actually fixed the issue, in case this is helpful to anyone, [here](https://github.com/itzg/docker-minecraft-bedrock-server/issues/26#issuecomment-580842017) is what I did to solve my problem. Thanks for the help!
