### ISSUE TITLE
Can't use Phantom on Termux/UserLAnd

### ISSUE THREAD

**Issue by ItzLightyHD** [jhead/phantom#91]
If I use UserLAnd or Termux, that are Linux environments, it should work on Android too, but it's not
![Screenshot_2020-06-09-20-25-26](https://user-images.githubusercontent.com/45460688/84185605-8c5a6100-aa8f-11ea-9f64-e1b63911260e.png)

**Comment by paptasos00** [comment]
@ItzLightyHD it's certainly the ARM version you should pick. As a matter of fact, I just tried the Linux ARM7 version out of curiosity and it works perfectly. Also I'd suggest Andronix instead of UserLand, as it has newer distro versions available.
![Screenshot_2020-06-10-10-40-40-464_com termux](https://user-images.githubusercontent.com/49914942/84243389-ce74b880-ab0a-11ea-9f8b-49c205f6cb17.jpg)

**Comment by paptasos00** [comment]
woops, did I just spoil my server's IP? Let's unfuck this real professionally

**Comment by paptasos00** [comment]
@ItzLightyHD it's certainly the ARM version you should pick. As a matter of fact, I just tried the Linux ARM7 version out of curiosity and it works perfectly. Also I'd suggest Andronix instead of UserLand, as it has newer distro versions available.
![arm7termux](https://user-images.githubusercontent.com/49914942/84244080-cec18380-ab0b-11ea-9284-33f62ce4f1fc.png)

**Comment by ItzLightyHD** [comment]
> What Android device are you using?

Huawei MYA-L11 with Android 6.0

**Comment by jhead** [comment]
ah looks like you might need ARM8. I built a new binary for 8, try that one? https://github.com/jhead/phantom/releases/tag/v0.5.1

**Comment by ItzLightyHD** [comment]
> ah looks like you might need ARM8. I built a new binary for 8, try that one? https://github.com/jhead/phantom/releases/tag/v0.5.1

Ok, i'll try. If something goes wrong, i'll write it here

**Comment by ItzLightyHD** [comment]
Ok, now it works. But can you tell me why if I try to use phantom to join HyperLands, it says me "Can't connect to the server"?

**Comment by jhead** [comment]
It might be related to some incompatibility with certain servers. Have you tried other servers? For example, there's a known bug with phantom connecting to servers running Nukkit.
